language: d

dist: trusty
sudo: required

d:
  - dmd-2.083.0
  - ldc
os:
  - linux
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=unittest

before_install:
  - sudo add-apt-repository ppa:jonathonf/backports -y
  - sudo apt-get update
  - sudo apt-get install sqlite3

matrix:
  include:
  - d: dmd-2.083.0
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd-2.083.0
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
      - sqlite3

script:
- ./travis.sh

notifications:
  mail:
    on_success: change
    on_failure: change
