language: d

d:
  - dmd-2.078.3
  - dmd-2.077.1
  - ldc
os:
  - linux
end:
  - BUILD_TYPE=debug
  - BUILD_TYPE=unittest

matrix:
  include:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
      - sqlite3-dev
      - sqlite3

script:
- ./travis.sh
