language: d

dist: trusty
sudo: required

services:
  - docker

before_install:
  - docker pull dlanguage/dmd
  - docker run -d -p 4567 dlanguage/dmd /bin/sh "sudo apt-get install sqlite3 dub"

d:
  - dmd-2.078.3
  - dmd-2.077.1
  - ldc
os:
  - linux
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=unittest

matrix:
  include:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd-2.078.3
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
      - sqlite3

script:
- ./travis.sh
