language: d

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
      - libsqlite3-dev
      
cache:
  directories:
    $HOME/.dub/

d:
  - dmd
  - ldc
  - gdc

notifications:
  email: false
