language: d

d:
  - dmd
  - ldc
os:
  - linux
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=unittest

matrix:
  include:
  - d: dmd
    env: BUILD_TYPE=unittest-cov
  exclude:
  - d: dmd
    env: BUILD_TYPE=unittest

addons:
  apt:
    packages:
      - libevent-dev
      - libssl-dev
      - sqlite3

script:
- ./travis.sh

notifications:
  mail:
    on_success: change
    on_failure: change
